name: CI

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: amd64
          - os: ubuntu-latest
            platform: linux
            arch: arm64
            # Use ARM64 runner if available in your GitHub plan
            # os: ubuntu-latest-arm64
          - os: macos-latest
            platform: darwin
            arch: amd64
          - os: macos-14  # Apple Silicon runner
            platform: darwin
            arch: arm64
          - os: windows-latest
            platform: windows
            arch: amd64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'  # Adjust to your Java version
          distribution: 'temurin'
          architecture: ${{ matrix.arch == 'arm64' && 'aarch64' || 'x64' }}

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.8.1
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Configure Bazel (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          cat >> .bazelrc.local << EOF
          # Enable persistent workers for better performance
          build --worker_sandboxing
          
          # Platform-specific optimizations
          build --local_cpu_resources=HOST_CPUS*0.75
          EOF

      - name: Configure Bazel (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          echo build --local_cpu_resources=HOST_CPUS*0.75 >> .bazelrc.local

      - name: Build project
        run: bazel build //src:Main

#      - name: Run tests
#        run: bazel test //...

      - name: Upload native binaries (if any)
        uses: actions/upload-artifact@v4
        if: runner.os != 'Windows'
        with:
          name: bazel-binaries-${{ matrix.platform }}-${{ matrix.arch }}
          path: |
            bazel-bin/**/!(*.runfiles_manifest|*.sh)
            !bazel-bin/**/*.jar

      - name: Upload native binaries (Windows)
        uses: actions/upload-artifact@v4
        if: runner.os == 'Windows'
        with:
          name: bazel-binaries-${{ matrix.platform }}-${{ matrix.arch }}
          path: bazel-bin/**/*.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bazel-build-${{ matrix.platform }}-${{ matrix.arch }}
          path: bazel-bin/**/*.jar
